[package]
name = "serial2screen"
version = "0.1.0"
authors = ["yesiot <goslawski.p@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
serial = "0.4"
show-image = "0.8.2"